#!/bin/bash
# 05b-vault-utils-storage.sh
# Storage setup functions for Vault deployment

# Function to setup storage for Vault
setup_vault_storage() {
  log "Setting up storage for Vault..."
  
  # Create the volume configuration if it doesn't exist
  if [ ! -f "${CONFIG_DIR}/volumes.hcl" ]; then
    log "Creating initial volume configuration..."
    mkdir -p "${CONFIG_DIR}"
    
    cat > "${CONFIG_DIR}/volumes.hcl" << EOF
# Nomad Volumes Configuration
# Generated by 05-deploy-vault.sh

# Standard volume
volume "standard" {
  type = "host"
  source = "standard"
  read_only = false
}

# High Performance volume
volume "high_performance" {
  type = "host"
  source = "high_performance"
  read_only = false
}

# High Capacity volume
volume "high_capacity" {
  type = "host"
  source = "high_capacity"
  read_only = false
}

# Vault data volume
volume "vault_data" {
  type = "host"
  source = "vault_data"
  read_only = false
}
EOF
    success "Created volume configuration file"
  else
    # Check if the vault_data volume is defined in the existing config
    if ! grep -q "volume \"vault_data\"" "${CONFIG_DIR}/volumes.hcl"; then
      log "Adding vault_data volume to existing volume configuration..."
      cat >> "${CONFIG_DIR}/volumes.hcl" << EOF

# Vault data volume
volume "vault_data" {
  type = "host"
  source = "vault_data"
  read_only = false
}
EOF
      success "Added vault_data volume to configuration"
    else
      log "vault_data volume already defined in configuration"
    fi
  fi
  
  # Create the host directories for the volume
  log "Creating host directory for vault_data volume: ${VAULT_DATA_DIR}"
  
  # Create data directory for vault with sudo if needed
  sudo mkdir -p "${VAULT_DATA_DIR}"
  sudo chmod 755 "${VAULT_DATA_DIR}"
  
  # Set permissions for Nomad access
  log "Setting permissions on Vault data directory for Nomad..."
  
  # First try to set ownership to nomad user
  if id nomad &>/dev/null; then
    sudo chown -R nomad:users "${VAULT_DATA_DIR}" 2>/dev/null || true
  fi
  
  # If that failed or nomad user doesn't exist, try current user
  if [ "$(stat -c '%U' "${VAULT_DATA_DIR}")" != "nomad" ]; then
    sudo chown -R $(whoami):$(id -gn) "${VAULT_DATA_DIR}" 2>/dev/null || true
    warn "Could not set ownership to nomad user. Using current user instead."
  fi
  
  # Register the volume in Nomad if not already registered
  log "Checking if vault_data volume needs to be registered in Nomad..."
  
  if ! nomad volume status vault_data &>/dev/null; then
    log "Registering vault_data volume in Nomad..."
    # Check if we should register all volumes or just the Vault volume
    
    echo -e "${YELLOW}Do you want to register all volumes in volumes.hcl or just the vault_data volume? [a]ll/[v]ault/${NC}"
    read -r register_choice
    
    if [[ "$register_choice" =~ ^([aA][lL][lL]|[aA])$ ]]; then
      # Register all volumes
      log "Registering all volumes from ${CONFIG_DIR}/volumes.hcl"
      nomad volume create "${CONFIG_DIR}/volumes.hcl" || warn "Failed to register all volumes. Will try just the vault_data volume."
    fi
    
    # If all volumes registration failed or user chose vault only, register just vault_data
    if ! nomad volume status vault_data &>/dev/null; then
      log "Registering just the vault_data volume in Nomad..."
      
      # Extract just the vault_data volume section from the config
      grep -A6 "volume \"vault_data\"" "${CONFIG_DIR}/volumes.hcl" > /tmp/vault_volume.hcl
      
      # Register the vault_data volume
      nomad volume create /tmp/vault_volume.hcl
      rm -f /tmp/vault_volume.hcl
    fi
    
    # Verify volume registration
    if nomad volume status vault_data &>/dev/null; then
      success "vault_data volume registered successfully in Nomad"
    else
      error "Failed to register vault_data volume in Nomad"
    fi
  else
    log "vault_data volume is already registered in Nomad"
  fi
  
  # Verify the volume is accessible
  log "Verifying vault_data volume is accessible..."
  if [ -d "${VAULT_DATA_DIR}" ] && [ -w "${VAULT_DATA_DIR}" ]; then
    success "vault_data volume is accessible and writable"
  else
    warn "vault_data volume directory exists but may not be writable by Nomad"
    log "This may cause problems when Vault tries to write data"
    log "You may need to manually fix permissions: sudo chmod -R 755 ${VAULT_DATA_DIR}"
  fi
  
  success "Vault storage setup completed"
}